[package]
name = "protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
limits = { path = "../limits" }
prost = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
