[package]
name = "discovery"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
limits = { path = "../limits" }
protocol = { path = "../protocol" }
mdns-sd = "0.11"
flume = { version = "0.11", default-features = false, features = ["async"] }
tokio = { workspace = true, features = ["sync", "time", "rt"] }
rand = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
