[package]
name = "crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
limits = { path = "../limits" }
ed25519-dalek = { workspace = true }
x25519-dalek = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
chacha20poly1305 = { workspace = true }
zeroize = { workspace = true }
rand = { workspace = true }
subtle = "2"
thiserror = { workspace = true }
